const String privacy6 = "SOCIAL MEDIA POLICY & USAGE";
const String packageTxt = "Enjoy our state-of-the-art facilities and services designed for holistic healing and wellness";
const String testimonialTxt = "I was experiencing serious chest pain and nausea so I decided to visit a local hospital in Haldwani,Uttarakhand from where I was referred to Sri Ram Moorti hospital and got my angiography done.";
const String aboutCenterTxt = "Experience cutting-edge heart care at the SAAOL Heart Center in Aligarh, specializing in innovative EECP treatment. Our center is dedicated to providing comprehensive care for patients facing heart diseases, including heart attack treatment, heart failure treatment, and heart disease management. We utilize advanced EECP therapy, also known as natural bypass therapy, delivering non-invasive solutions for patients with heart blockages, aiming to reverse heart disease and promote natural heart healing. At our state-of-the-art facility, we prioritize patient well-being by providing a range of services beyond EECP treatment. Our holistic approach includes detox therapy to support overall cardiovascular health and detoxification therapy treatment to address underlying factors contributing to heart disease. With a focus on non-invasive techniques, our center aims to provide effective cardio treatment for conditions such as coronary artery disease, ensuring optimal outcomes with minimal risk. Trust our experienced team at the Heart Center in Aligarh to deliver personalized care and transformative results for your heart health journey.";
const String benefit1 = "Unlike bypass surgery, EECP Therapy is non-invasive, meaning there are no incisions or cuts involved. Patients experience no trauma to the body, resulting in a quicker recovery time and minimal discomfort.";
const String benefit2 = "EECP Therapy is entirely painless. Patients can undergo treatment comfortably without the need for anesthesia or sedation. This eliminates the risks associated with anesthesia and post-operative pain management.";
const String benefit3 = "EECP Therapy is typically performed on an outpatient basis, meaning there's no need for hospitalization. Patients can return home immediately after treatment sessions, allowing them to resume their daily activities without interruption.";
const String benefit4 = "Since EECP Therapy doesn't involve any surgical incisions, the risk of infection is significantly reduced. Patients can undergo treatment with peace of mind, knowing that there's no risk of post-procedural complications.";
const String benefit5 = "EECP Therapy is associated with minimal to no side effects. Unlike traditional bypass surgeries, which can cause various adverse effects such as bleeding, infection, and allergic reactions to anesthesia, EECP Therapy provides a safe and well-tolerated alternative.";
const String benefit6 = "EECP Therapy is a cost-effective treatment option compared to bypass surgery (CABG). It eliminates the need for hospitalization, anesthesia, and post-operative care, resulting in lower overall healthcare costs for patients.";
const String aboutEECP = "Discover the power of EECP treatment, also called natural bypass therapy, for those seeking non-surgical heart attack treatments in Aligarh. Our mission is to treat and reverse heart disease effectively through non-invasive procedures. Find affordable solutions for a healthier heart journey with us.";
const String treatmentOverviewTxt = "SAAOL, has created a forte as the world’s largest chain of non-invasive heart centers having helped over 500,000 patients with a history of unsuccessful heart operations, re-blockages, low ejection fractions, etc. Our specialists are experts in diagnosing different heart problems without using any invasive methods such as any kind of fluid, injection, etc. Our treatment approach is based on allopathic modern medicine, fact-based medical tests, healthy dietary advice and lifestyle management which is far better and easy than surgical interventions.";
const String aboutEECPTxt = "Discover an innovative, non-invasive solution to enhance heart well-being and address cardiac blockages: EECP therapy. Immerse yourself in the forefront of medical progress at the SAAOL Heart Center, where state-of-the-art EECP treatment is meticulously designed to optimize blood circulation and promote comprehensive cardiovascular health.";
const String advantageTxt1 = "rigorously researched, clinically proven and FDA approved regimen that enhances heart functionality by boosting blood flow to the coronary arteries.";
const String advantageTxt2 = "compared to traditional surgeries as it uses inflatable cuffs wrapped around the legs, synchronized inflation and deflation in rhythm with the heartbeat.";
const String advantageTxt3 = "by increasing the heart muscle’s access to essential blood supply.";
const String advantageTxt4 = "right after 1 session resulting in elevated energy levels and an overall sense of well-being.";
const String advantageTxt5 = "leads to higher oxygen and nutrient delivery to tissues.";
const String therapyTxt = "EECP therapy extends a compelling invitation for those navigating distinct challenges or personal preferences in their quest to address heart-relate issues. The following eligibility criteria shed light on who stands to benefit from EECP therapy:";
const String therapyTxt1 = "EECP therapy emerges as a particularly pertinent choice for individuals who do not meet the prerequisites for invasive interventions like surgical procedures. It presents an alternative avenue for tackling heart-relate ailments.";
const String therapyTxt2 = "EECP therapy proves invaluable for individuals carrying an elevated risk due to concurrent medical conditions. It serves as a non-invasive lifeline for those at risk of complications associated with surgical interventions.";
const String therapyTxt3 = "EECP therapy emerges as a particularly pertinent choice for individuals who do not meet the prerequisites for invasive interventions like surgical procedures. It presents an alternative avenue for tackling heart-relate ailments.";
const String therapyTxt4 = "When conventional medications fail to deliver the desired relief from angina or other heart-related symptoms, EECP therapy opens the door to renewed possibilities for enhanced heart health.";
const String therapyTxt5 = "EECP therapy steps forward as an effective option for individuals contending with the resurgence of symptoms following invasive treatments like angioplasty, stenting, or bypass surgery.";
const String therapyTxt6 = "EECP Therapy presents a viable and secure alternative for individuals whose medical conditions renders surgery impractical or places them at a substantial risk of postoperative complications.";
const String therapyTxt7 = "EECP therapy caters to those experiencing enduring chest pressure or discomfort, which varies with stress or physical exertion. It offers relief and contributes to overall heart wellness.";
const String therapyTxt8 = "When an individual’s coronary structure poses complexities that impede the efficacy or escalate the risks associated with conventional treatments, EECP therapy steps in as a pragmatic and efficacious solution.";
const String preparingEECPTxt = "Before you embark on you Enhanced External Counterpulsation (EECP) therapy, a series of vital steps and preparations ensure a smooth and effective experience. Your path to improved heart health begins with thorough evaluation and thoughtful planning:";
const String preparingEECPTxt1 = "Medical Evaluation conducted by skilled healthcare professional. This assessment is to know your medical history, current health status, and the specific heart condition you are facing. The goal is to determine whether EECP is suitable and beneficial option to your needs.";
const String preparingEECPTxt2 = "Informative session to receive detailed information about EECP therapy. This session will equip you with a clear understanding of what to expect during the therapy, its potential benefits, and addresses any questions or concerns you may have.Health Monitoring throughout your EECP therapy sessions. Your vital signs, including blood pressure and heart rate, are closely monitored to ensure your safety and comfort throughout the process.";
const String preparingEECPTxt3 = "Setup for Best Comfort, reclining position on a specialised treatment bed. Large cuffs, like blood pressure cuffs but designed for precision, are gently secured around your calves, thighs and buttocks.";
const String preparingEECPTxt4 = "The therapy begins as these cuffs inflate and deflate in a synchronised manner, aligning with your own heartbeat. This inflation-deflation process assists in enhancing blood flow back to your heart, thereby reducing its workload and fastens healing.A typical EECP session is about an hour. During this time, you are encouraged to relax and unwind. Many individuals choose to read, watch TV, listen to music, or simply enjoy their peace time.A complete EECP course typically includes 35 sessions, scheduled over five days each week. This regimen extends over several weeks to optimize its benefits.";
const String preparingEECPTxt5 = "For many individuals, the positive effects of EECP therapy become evident even after just a few sessions. Reduced chest discomfort, increased vitality, and an overeall sense of wek-being often emerge as immediate benefits of EECP treatment.EECP treatment is an inspiration for positive lifestyle adjustments. Patients often find themselves adopting heart-healthy diets, embracing regular exercise routines, and incorporating stress management practices into their daily lives.Long-Term Benefits of EECP treatment like improved blood circulation, no more angina symptoms, and an enhanced quality of life are enduring advantages.Your healthcare team will arrange follow-up appointments to monitor your progress and address any further steps required to safeguard and enhance your heart health.";
const String preparingEECPTxt6 = "To get the full and remarkable benefits of EECP, it is important to continue practicing heart-healthy habits. This includes maintaining regular exercise, having a balanced diet, and, if prescribed, staying committed to your prescribed medication program.Remember, EECP treatment important treatment for your heart health. Ongoing communication with your healthcare professional and following their recommendations should be prioritized as it helps with your long-term well-being.";
const String healthyFoodTxt = "Some famous and delicious Indian dishes like appe, chilla, chole bhature, chocolate cake, kachori, veg biryani, balushahi, aloo tikki, and many more. Indians don’t know much about zero oil cooking recipes. To teach people how to do cooking without oil and make delicious dishes like these, we have our own Youtube Channel named “SAAOL’s Zero Oil Kitchen”. We have some expert dieticians and nutritionists who will show and explain every step in detail on how to cook delicious food healthily. Some recipes without oil are discussed below.";
const String safetyTxt = "This scientifically proven chart can be used by heart patients to check the status of their disease control. It contains 16 spokes in a wheel where each spoke represents a risk factor with parameters like cholesterol, triglycerides, cholesterol/HDL ratio, BP, sugar control, BMI, tobacco consumption, walking, intake of fats/ oils, consumption of fruits and vegetables, intake of animal foods, Yoga-based exercises, meditation, and stress management. There are three zones in this chart:";
const String aboutSir = "Dr.Bimal Chhajer MBBS,MD is a well-known personality in the world of medical science in India and abroad. He is the pioneer of Non-invasive cardiology in India.";
const String aboutBimalSir = "Dr. Bimal Chhajer MBBS,MD is a well-known personality in the world of medical science in India and abroad.He is the pioneer of Non-invasive cardiology in India. Born in 1961 in a Jain family, Dr. Chhajer grew up in a small village in West Bengal and passed his matriculation with flying colours from a local school.";

const String paragraph = "A well-organized paragraph supports or develops a single controlling idea, which is expressed in a sentence called the topic sentence. A topic sentence has several important functions: it substantiates or supports an essay’s thesis statement; it unifies the content of a paragraph and directs the order of the sentences; and it advises the reader of the subject to be discussed and how the paragraph will discuss it. Readers generally look to the first few sentences in a paragraph to determine the subject and perspective of the paragraph. That’s why it’s often best to put the topic sentence at the very beginning of the paragraph. In some cases, however, it’s more effective to place another sentence before the topic sentence—for example, a sentence linking the current paragraph to the previous one, or one providing background information.";
const String blogTxt1 = "Heart health is paramount, yet it’s overlooked until problems arise. Understanding and undergoing essential heart tests can be a game-changer in early detection and prevention. This blog explores the crucial heart tests for blockage, their benefits, and how they help safeguard your heart health.";
const String blogTxt2 = "Heart blockages, primarily due to coronary artery disease, are a leading cause of heart problems. These blockages occur when cholesterol and fatty deposits build up in the arteries, restricting blood flow to the heart. Early detection through heart tests for blockage is crucial in preventing severe heart conditions. These tests identify potential issues, allowing for timely management and better heart health.";
const String blogTxt3 = "Early detection of heart problems can significantly reduce the risk of severe complications. By identifying issues early, you can take proactive steps to improve your heart health and prevent the progression of heart disease. Here are some non-invasive heart tests essential for early detection.";
const String blogTxt4 = "An Electrocardiogram (ECG) measures the electrical activity of your heart. This test helps identify irregularities in heart rhythm, heart rate, and other cardiac issues. It’s quick, non-invasive, and provides immediate results, making it an essential tool for diagnosing heart problems.";
const String blogTxt5 = "The Exercise Stress Test, also known as the Treadmill Test (TMT), evaluates how your heart performs under physical stress. By monitoring your heart rate, blood pressure, and ECG during exercise, this test helps detect heart blockages and coronary artery disease.";
const String blogTxt6 = "Holter monitoring involves wearing a portable device that continuously records your heart’s electrical activity for 24 to 48 hours. It’s particularly useful for detecting irregular heartbeats, palpitations, and unexplained fainting spells that may not appear during a standard ECG.";
const String blogTxt7 = "The Treadmill Test (TMT) is another name for the Exercise Stress Test. This non-invasive test assesses how your heart responds to physical exertion. Monitoring ECG, heart rate, and blood pressure during the test can reveal issues such as coronary artery disease and other heart conditions.";
const String blogTxt8 = "Thallium and PET scans are nuclear imaging tests that evaluate blood flow to the heart muscle. They help detect areas of poor blood flow, which can indicate blockages or damaged heart tissue. These tests are particularly useful in assessing the severity of coronary artery disease.";
const String aboutHearAttackTxt = "The most common complication of heart blockages—heart attack results in acute chest pain or breathlessness at rest. It is caused by 100% blockage of any of the coronary arteries. Simply put, the growing blockage stretches the membrane (Intima) covering the heart and ultimately rapturing it. Then clotting chemicals are released in the flowing blood making a clot that instantly stops the complete blood supply of the muscle getting from that particular tube. It happens suddenly and can kill a person suddenly. Heart Attacks may be minor, major, or massive depending on the location of the blockage. But is it preventable? –Yes with 98% surety!";
const String aboutTxtHeart = "Blood pressure is the measurement of the pressure or force of blood pushing against blood vessel walls. In high blood pressure (hypertension), this pressure against the blood vessel walls is consistently too high. High blood pressure is often called the ‘silent killer’ because you may not be aware that anything is wrong, but the damage is occurring within your body. The only way to find out if your blood pressure is high is to have your pressure checked. Untreated hypertension can increase your risk of stroke, heart failure, kidney failure, and other conditions.";
const String riskTxt = "If your blood pressure is too high, it puts added stress on your blood vessels, heart, and other organs, such as the brain, kidneys, and eyes. Persistent high blood pressure can surge your risk of a number of severe and potentially life-threatening health conditions such as heart diseases, heart attack, strokes, heart failure, peripheral arterial disease, aortic aneurysms, kidney diseases, and vascular dementia. If you have high blood pressure, reducing it to even a small amount can help lower your risk of these health conditions.";
const String treatmentTxt = "At Saaol we believe in non-invasive treatment methods that include education and lifestyle management, optimum allopathic medical management, and saaol detox therapy. We believe in effectively treating and reversing the condition by non-invasive methods. It is a combination of all-natural techniques to treat heart health conditions. We are promoters of yoga for heart and zero oil cooking. We have also created a Saaol safety circle to monitor how well are the hearth patients doing in their efforts.";
const String causesTxt = "High blood pressure, high blood cholesterol and smoking are key risks factors for heart disease. Several other medical conditions and lifestyle choice can put people at a higher risk for heart disease, including:";
const String causesTxt2 = "Heart disease is a common health problem. There are several types of heart diseases. In many cases, a person can take steps to prevent heart disease and its complications. The mission of Saaol is to effectively treat and reverse heart disease in a series of non-invasive or non-operative ways.";
const String riskFactorTxt = "Risk factors are the reasons, which lead to or aggravate the deposition of cholesterol or fat in the coronary arteries. There are innumerable risks factors for coronary heart disease. Williams in 1981 identified 246 risk factors that directly or indirectly lead to the development and onset of heart diseases.";
const String healthierTxt = "Nearly 20 crores under 30 years of age are hypertensive patients in India and 19% of the total deaths each year are related to heart disease. Detailed estimates from 1990 to 2016 of heart and blood vessel diseases in every state of India show that these diseases have increased. Many are struggling to recover from heart attack or stroke, while others at high risk are getting the care and making the changes necessary to lower their risk. The fact is, you can do plenty for your hearth health, even if you’ve had a bad experience. Healthy lifestyle changes will help you feel and look better! Start today to take control over your future. You’ll find that once you make one change, you are a step closer towards healthy living.";
const String ageTxt = "The incidence of heart disease increases with advancing age but today we are seeing people getting heart attack at a younger age.";
const String sexTxt = "Men are at a greater risk of heart attacks as compared to women but due to excessive stress more women are getting prone to heart diseases.";
const String heredityTxt = "People with a strong family history of heart disease are at a greater risk. But early prevention can surely decrease the risk.";
const String chestPainTxt = "victim of a heart attack often complaints of an excruciating pain in the left part of the chest, radiating to the left arm. The pain is not relieved by taking rest or sorbitrate (or other nitrates) below the tongue.";
const String intenseFeelingTxt = "In many patients there is a feeling of intense emptiness or giddiness following a heart attack. Some of the patients feel the same as in case of a low blood pressure and low blood sugar.";
const String suffocationTxt = "Choking, sense of constriction in the chest. There may be feeling of breathlessness in some patients. Those who already have angina, would find worsening of the symptoms.";
const String burningSensationTxt = "This feeling occurs specially in people having heart attack for the first time. This uncomfortable feeling, accompanied with a gastric or acidity problem, many times confuse heart attack victims. They consider this as a gas problem and take some antacid tablets, which also relieve the feeling to some extent.";
const String preventAttackTxt = "The simple message is ‘Do not create more blockages. If you can reduce it, heart attack would never occur.’ It is like a bundle of notes being guarded by a rubber band. If you keep on putting more and more notes inside the rubber band one day the rubber band will break. This is the situation of a heart attack where the membrane also breaks off. Now if you stop putting more notes, the rubber band will never break. Further, if you start taking out one or two notes from the bundle every day, the rubber band will never break. The same principle applies in prevention of heart attack. By controlling all the risk factors of heart disease by adequate changes in the lifestyle can prevent heart attacks. The following are the expected parameters to prevent heart attacks:";
const String newsTitle = "We're thrilled to announce the inauguration of the latest SAAOL Heart Center in Itanagar Arunachal Pradesh! Our mission to prioritize your cardiovascular health has led us to expand our reach,....";
const String magaZineTxt1 = "When it comes to staying healthy, your heart deserves top priority. Cardiovascular wellness is not just a medical concern; it's a lifestyle choice that significantly impacts your overall well-being. By adopting a heart-nourishing lifestyle, you can ensure your heart remains strong and resilient.";
const String conclusionTxt = "Adopting a heart-nourishing lifestyle is a journey worth embarking on. You can significantly improve your cardiovascular wellness by prioritizing diet, exercise, and mental well-being and avoiding harmful habits. Remember, your heart is at the center of your health, so take the steps today to ensure it stays healthy and strong.";
const String privacyPolicyTxt = "We collect information about you when you visit our Website and/ or through your physical interaction with our staff. The type of information which we generally collect is your name, address, age, sex or medical report(s)/ history, physical, physiological and mental health condition or any other information as required to provide you desired services. We will not disclose above information to any other person unless required for providing you the desired services or required under the Law or if the information is already in public domain. You may choose to not provide any sensitive information to us if you feel and find it to be confidential/sensitive. We use one of the prominent payment gateway to collect or refund the payment. And we never collect bank/credit card information of the Information Provider. You are deemed to have provided your consent to share the information with concerned persons while providing you the desired services as above. You may withdraw your consent in writing at any time and we shall have the option not to provide the services for which information was provided.";
const String privacyDataSecurityTxt = "The information collected from you by us is secured and can be accessed by the authorized persons only. We have implemented adequate security practices and standards with necessary controls commensurate with the information being provided.";
const String privacyInformationTxt = "We may use the information shared by you for the purpose of providing various services offered by the Hospital.";
const String privacySharingInformationTxt = "We may share your information with concerned persons who need to use the same for authorised purpose / providing desired services to protect and defend the right and property of Hospital. Wherever required by law / Govt. Agencies with you if you may desire so subsequently. The information shared by you shall not be displayed by us for any promotional activity. We shall address any discrepancies and grievances of the provider of the information with respect to the processing of information in a time-bound manner. For this purpose, we have designated person who acts as Grievance Officer of the Company.";
const String applicabilityTxt = "We may share your information with concerned persons who need to use the same for authorised purpose / providing desired services to protect and defend the right and property of Hospital. Wherever required by law / Govt. Agencies with you if you may desire so subsequently. The information shared by you shall not be displayed by us for any promotional activity. We shall address any discrepancies and grievances of the provider of the information with respect to the processing of information in a time-bound manner. For this purpose, we have designated person who acts as Grievance Officer of the Company.";
const String informationTxt1 = "We require you to provide us with certain information about yourself when you use the Online Transactions. This information shall include patient’s details and card holder’s name in case of online payment facility. We may also use this information to ensure that the bill payment process is carried out accurately and efficiently.";
const String informationTxt2 = "You agree to ensure that any information provided by you shall be complete and accurate. You shall not at any time provide us with information which is false, inaccurate, misleading, obsolete or deceptive. If the information is found false/ deceptive/inaccurate/misleading, SAAOL Heart Center holds right to cancel the appointment/ transaction and refund/stop the payment.";
const String informationTxt3 = "All information provided by you should be true, complete and accurate but not misleading or deceptive;";
const String informationTxt4 = "To receive the confirmation alert of the appointment booking, kindly provide your correct contact number. By providing the said information, you hereby authorise SAAOL Heart Center to contact you via, telephonic calls, SMS in respect of the appointments booked by you and for providing the information about the services provided by SAAOL Heart Center, to you.";
const String informationTxt5 = "The consultation time provided is indicative and actual consultation time may vary.";
const String informationTxt6 = "Appointment booking is only for consultation and for follow up consultation.";
const String informationTxt7 = "A registration charge will be applicable for new patients. Registration amount will not be refunded under any circumstances.";
const String informationTxt8 = "Any changes or cancellation in the appointment should be done by calling the hospital number provided or SMS.";
const String informationTxt9 = "The appointment slot will be released in case of late arrival of the patient and the patient will be treated as a walk-in patient and consultation should be subject to availability of time with the respective doctor.";
const String informationTxt10 = "Complete details of ‘New’ patient should be filled accurately and we may also use this information for data analysis and marketing purposes. By accepting these Terms, you expressly permit SAAOL Heart Center to use the data provided by you for the said purpose.";
const String informationTxt11 = "We track the Internet address of the domains from which people visit us for trend analysis.";
const String informationTxt12 = "We may use the Internet address to identify any fraudulent transaction.";
const String informationTxt13 = "If you do not wish to provide us with the required information, kindly click on exit button to exit the appointment booking application.";
const String hyperlinkThirdPartyTxt = "This Website provides links to other sites by allowing the user to leave this WebSite to access website of Developer of their website (a “Hyper-Link Site”) or third party websites for the users’ convenience. Hyper-Link Sites and third party sites may contain rules, regulations, privacy and other provisions which may be markedly different from the provisions provided on the WebSite. Access to Hyper-Link Sites or third party websites or any other internet sites linked to the Website is at the user’s own risk. SAAOL Heart Center is not responsible for the content or accuracy or correctness of such information and provisions and specifically disclaims any and all related liability. Access to a Hyper-Link Site does not imply any direct or indirect endorsement by SAAOL Heart Center of the Hyper-Linked Site or products and services offered therein. All the transactions on such Hyper-Link Sites shall be governed by the terms & conditions of usage of the respective Hyper Link Site.";
const String availabilityTxtContent = "SAAOL Heart Center operates and controls this WebSite from India and makes no representations that the Information is appropriate for use in any other location across the globe. Information published in this WebSite may contain references to products and services which are available in India and not available in your country. Such references do not imply that SAAOL Heart Center intends to make available such products or services in your country. Users are urged to consult SAAOL Heart Center officials for information regarding the products and services available to you";
const String intellectualTxt = "The contents of this WebSite are protected by applicable intellectual property laws of India including without limitation to trademark and copyright laws. Reproduction, retransmission, public and/or commercial use of any or all the material on this WebSite is prohibited. The logos, service marks and trademarks (“IP Marks”) displayed on the WebSite are the property of SAAOL Heart Center. Nothing on this WebSite should be construed as granting, by implication, estoppels, or otherwise, any license or right to use any trademarks without our written permission. You are prohibited from using any IP Marks for any purpose without the written permission of SAAOL Heart Center. You may use, display, and print copies of the Information only on your personal computer only for your personal non-commercial purpose and use. You are prohibited from modifying, copying, distributing, transmitting, displaying, publishing, selling, licensing, creating derivative works or using any Information available on or through the WebSite for commercial or public purposes, in contravention of the above permitted use.";
const String limitationTxt = "The information available on the site WebSite could include inaccuracies or typographic errors. SAAOL Heart Center specifically"
    " disclaims any liability for such inaccuracies or errors. SAAOL Heart Center does not warrant"
    " or represent that the information on the website is complete"
    " or up-to-date, and assumes no obligation to update the website. "
    "SAAOL Heart Center may change the information on the website at "
    "any time without notice or may make improvements or changes to the website at any time. "
    "You agree and undertake that SAAOL Heart Center, its affiliates, "
    "and any of their respective officers, Trustees, Board Members, directors,"
    " employees, or agents will not be liable, whether in contract, tort,"
    " strict liability or otherwise, for any direct, punitive, special, "
    "consequential, incidental or indirect damages (including without limitation "
    "lost profits or lost opportunity) arising out of or in connection with the "
    "use of this WebSite website or a Hyperlink Site or a third party site,"
    " or with delay or inability to use the website or a Hyperlink Site,"
    " even if SAAOL Heart Center is made aware of the possibility of such damages. "
    "This limitation on liability includes, but is not limited to, the transmission "
    "of any viruses which may infect a user’s equipment, unauthorized access, "
    "operator errors, theft, failure of mechanical or electronic equipment or "
    "communication lines, telephone or other connection problems, strikes or "
    "other labor problems or any force majeure. SAAOL Heart Center cannot"
    " and does not guarantee continuous, uninterrupted, or secure access"
    " to the website. You are informed that use of the internet may be "
    "susceptible to a number of frauds, misuse, hacking, and other actions "
    "that could affect payment instructions / other instructions to your "
    "bank through the payment gateway. SAAOL Heart Center shall aim to provide"
    " security to prevent the same, there cannot be any guarantee from such"
    " internet frauds, hacking, and other actions that could affect payment instructions /"
    " other instructions including resulting in delay or failure in processing the "
    "instructions. SAAOL Heart Center shall not be responsible for the same. "
    "SAAOL Heart Center shall not be responsible for any such failed transaction,"
    " where the bank account of the user of the WebSite is debited for the transaction "
    "amount and the transaction is not completed, for any reason whatsoever."
    " Such user should connect with his/her banker for any such failed "
    "transactions and the user of WebSite absolves SAAOL Heart Center "
    "of any liability, whatsoever, on this account.";
const String dataProtectionTxt1 = "SAAOL Heart Center may use “Cookies” for storing visitor preferences, profiling visitors and tracking visitor behavior on this WebSite. Cookies are small data files that a WebSite stores on computer. By visiting this WebSite you acknowledge, accept and expressly authorize SAAOL Heart Center for the placement of Cookies on your computer.";
const String dataProtectionTxt2 = "SAAOL Heart Center shall take all reasonable precautions to preserve the confidentiality and prevent any corruption or loss, damage or destruction of the data and information provided by you on the WebSite.";
const String dataProtectionTxt3 = "All personal medical information will be kept confidential. It will only be disclosed to those involved with your treatment or care or persons involved in the process of evaluation of your information including but not limited to medical treatment, procedure, services etc. or an organization, which may be responsible to evaluate your treatment expenses. However, SAAOL Heart Center reserves the right to perform statistical analyse on your personal data and information. For details on the confidentially and privacy policy refer to the Online Privacy Statement. If such data has been requisitioned by any government agency/department/body and/or any law enforcement agency, SAAOL Heart Center shall be entitled to share the same on receipt of a written notice in this regard.";
const String dataProtectionTxt4 = "Certain services on the WebSite may require authentication procedures and enable you to access such services by using a user ID and password. SAAOL Heart Center shall take reasonable care to ensure the security of and to prevent unauthorized access to the services, which are part of the WebSite, however you will be the sole and exclusive owner of user ID and the password. It is your responsibility to ensure the confidentiality and protection of your user ID and password and will not reveal to any third party. You are urged to change your password at regular intervals. In addition to user ID and password, SAAOL Heart Center may, at its discretion, require you to adopt such other means of authentication.";
const String dataProtectionTxt5 = "You are cautioned that use of cyber-cafe/shared computer for payment transaction at a shared terminal is risky and you are urged not to use a cyber-cafe/shared computer terminal for any such transactions.";
const String gatewayTxt1 = "We wish to make your payment process a secure and convenient experience, and invite you to carefully read these Terms and Conditions which govern the use of this Online Payment Facility.";
const String gatewayTxt2 = "We use all reasonable endeavors to ensure the integrity of the Online Payment Facility’s Security. Despite our endeavors breaches of security and confidentiality could occur. You acknowledge that we are not liable for any loss suffered by you as a result of any breaches in security.";
const String gatewayTxt3 = "You are responsible for keeping the computer you are making the payment from free from viruses and malicious programs, and maintaining all appropriate security measures.";
const String gatewayTxt4 = "You acknowledge that your failure to do so may lead to, amongst other things, the interception of data by unauthorized parties. We shall have no liability to you whatsoever if you suffer any loss that is caused wholly or in part by your failure to keep secure the computer you are making a payment from.";
const String gatewayTxt5 = "SAAOL Heart Center may at any time modify the Terms & Conditions of Use of the site without any prior notification to you. You can access the latest version of the User Agreement at any given time on the website. You should regularly review the Terms & Conditions on the website. In the event the modified Terms & Conditions is not acceptable to you, you should discontinue using the service. However, if you continue to use the service you shall be deemed to have agreed to accept and abide by the modified Terms & Conditions of Use of this site.";
const String paymentTxt = "When SAAOL Heart Center receives a transaction instruction from you in respect of any services or products on the WebSite, through appropriate mode, SAAOL Heart Center will be entitled to debit any payment plus any charges payable for the transaction from the account you have specified. You may also be directed to a third party site to enable processing of a transaction in which event such transaction will be governed by the terms and conditions of such third party site. SAAOL Heart Center shall not be liable (a) if any transaction does not fructify or may not be completed or (b) for any failure on part of the bank or the credit card or the third party site or agency to perform any of its obligations or (c) in respect of any loss or damage arising directly or indirectly out of the decline or acceptance of authorization for any transaction, for any reason whatsoever.";
const String generalTermsTxt1 = "Unauthorized use of any materials contained on this WebSite may violate the laws of intellectual property rights, the laws of privacy and publicity, and other applicable laws. You alone are responsible for your actions. As such, you shall indemnify and hold SAAOL Heart Center, its officers, directors, employees, affiliates, agents, and licensors harmless from and against any and all loss, costs, damages, liabilities, and expenses (including attorneys’ fees) incurred in relation to, arising from any claim or demand (including third party claims or demand) for violation caused by your actions or access, or, misuse of your user ID and password during use of the WebSite or any non-compliance with the Terms hereof or any unauthorized use of, this WebSite by you or someone using your computer.";
const String generalTermsTxt2 = "SAAOL Heart Center may change the Terms set out above from time to time. By browsing this WebSite you are accepting that you are bound by the current Terms and we urge you to check these each time you revisit the WebSite.";
const String generalTermsTxt3 = "SAAOL Heart Center may change the format and Information of this WebSite at any time. We reserve the right to add to or supersede certain provisions of these Terms with other provisions and reserve the right to revise the Terms at any time, at our sole discretion and without any prior notice. At no given time can we guarantee the information to be up to date. Users are deemed to be apprised of and bound by any changes to these Terms.";
const String generalTermsTxt4 = "SAAOL Heart Center prohibits unauthorized hypertext links and caching to the WebSite and reserves the right to disable any unauthorized links, third party links and disclaims any responsibility for information available on any other internet sites linked to the WebSite without due authorization.";
const String generalTermsTxt5 = "SAAOL Heart Center may suspend the operation of this WebSite for support or maintenance work, in order to update the Information or for any other reason.";
const String generalTermsTxt6 = "By visiting this WebSite, you agree to permit SAAOL Heart Center to communicate with you, from time to time, about our products and services, unless you decide to unsubscribe from receipt of such communications by following instructions stated therein. This may involve interruption of or stoppage linked services.";
const String generalTermsTxt7 = "SAAOL Heart Center shall not be liable if any transaction does not materialize"
    " or may not be completed or for any failure on its part to perform "
    "any of its obligations in respect of any products, policies or"
    " services, if the same is prevented, hindered or delayed by a "
    "Force Majeure Event. In such case its obligations shall be suspended "
    "for so long as the Force Majeure Event continues. For the purpose of "
    "this WebSite, a “Force Majeure Event” means any event due to any cause"
    " beyond the reasonable control of the SAAOL Heart Center, including without "
    "limitations, sabotage, fire, flood, explosion, acts of god, civil"
    " commotion, strikes or industrial action of any kind, riots, insurrection, "
    "war, acts of government, faults or failures in telecommunication, "
    "unavailability of any communication systems, breach, or virus in "
    "the processes or payment or delivery mechanism, computer hacking, "
    "computer crashes, malfunctioning in the computer terminal or the"
    " systems getting affected by any malicious, unauthorized access to"
    " computer data and storage devices, destructive or corrupting code "
    "or program, mechanical or technical errors/failures or power shut down,"
    " etc. Should this occur, we will attempt to contact you and refund "
    "the full amount.";

const String forwardInformationTxt = "Certain information on this WebSite may contain forward-looking statements, which are subject to risks and uncertainties. Users are cautioned not to place undue reliance on these forward-looking statements, which speak only as of the date on which they are made. The expressions “believe”, “expect”, “intend”, “aim”, “will” or similar expressions are intended to identify forward-looking statements. SAAOL Heart Center undertakes no obligation to update or revise any forward-looking statements";
const String pressTxt  = "All press releases and other materials contained on the WebSite are, to the best of SAAOL Heart Center’s knowledge, timely and accurate when issued. However, the passage of time can render information stale, and you should not rely on the continued accuracy of any such material beyond the date of issuance. SAAOL Heart Center has no responsibility to update any information contained in any such material. All viewers should carefully check the dates of issuance of the material contained in the WebSite.";
const String violationTxt = "SAAOL Heart Center reserves the right to seek all remedies available at law and in equity for violations of these Terms, including the right to block access from or to a particular Internet address to the WebSite.";
const String jurisdictionTxt = "The use of this WebSite by any one is subject to its terms and conditions, applicable Indian laws and government notifications, rules, regulations and guidelines issued by the Insurance Regulatory and Development Authority and other regulatory, governmental, and/or statutory bodies. Users of this WebSite agree to submit to the exclusive jurisdiction of courts at the State of Delhi alone in respect hereof.";
const String aboutSAAOLTxt = "SAAOL mission is to reduce the mortality rate due to heart disease related deaths and provide holistic heart care treatment and approach through natural bypass therapy, FDA approved non-invasive heart treatment like EECP and lifestyle changes. SAAOL Heart Centers are spread all over India so that people can have access to best heart treatment in India without travelling to Indian cities. Our heart specialists are trained under world renowned cardiologist Dr. Bimal Chhajer MBBS, MD (former AIIMS resident & associate professor). SAAOL ultimate purpose is to provide the best heart treatment and eradicate heart disease related deaths in India and then the world. Motto: Mission Beat Heart Disease.";
const String  visionTxt = "SAAOL’s vision is to ensure ‘Healthier Lifestyle and Risk Factor Reduction’. It aims to reduce the risk of heart disease through changes in Lifestyle which includes Diet Modification including Zero Oil Cooking, Stress Management, Exercise, Yoga, Meditation, Health Education and Counselling.";
const String missionTxt = "The mission of Saaol is to effectively treat and reverse heart disease by a series of non-invasive or non-operative ways. It combines all possible natural methods to treat heart disease and applies a simple theory of rectifying the causes of heart disease.";
const String valuesTxt = "To collaborate as a team and take extreme ownership of our audacious goals to achieve targets and display tremendous Integrity.";
const String aboutBimalSirTxt = "Dr. Bimal Chhajer MBBS, MD is a well-known personality in the world of medical science in India and abroad. He is the pioneer of Non-invasive cardiology in India. Born in 1961 in a Jain family, Dr. Chhajer grew up in a small village in West Bengal and passed his matriculation with flying colours from a local school. He studied in St. Lawrence high school in Kolkata thereafter and in 1986 pursued his MBBS from R.G. Kar Medical College, Kolkata. At the age of 25, he shifted to Delhi, where he started working in the cardiology department in Dr. Ram Manohar Lohia Hospital, New Delhi. A particular incident changed his life here and reformed his idea about the treatment of cardiac patients. He started advocating non-invasive or preventive cardiology. He then completed his MD in 1989 from king George’s Medical College, Lucknow where he took up a research study to treat heart patients using non-Invasive methods.";
const String aboutBimalSirTxt1 = "Post MD he worked at the famous All India Institute of Medical Sciences (AIIMS) for six years (1989-1995) as a Senior Resident and as an Assistant Professor. "
    "He also got training in yoga therapy. His research at the AIIMS"
    " showed that not only heart patients could prevent coronary"
    " heart disease but can also reverse or cure heart disease."
    " Dr. Chhajer during this stint also got trained by Dr."
    " Dean Ornish, who pioneered the lifestyle treatment in USA."
    " In 1995 based on his past research, Dr. Bimal chhajer resigned "
    "from AIIMS and started practically training and treating heart"
    " patients by his new treatment called “SAAOL” Science And Art Of "
    "Living in Delhi. In 1996 Dr. Chhajer opened his second clinic in "
    "Mumbai and subsequently expanded to Kolkata, Chennai, Bangalore"
    " and Hyderabad. These were followed by a spread of Saaol Centers"
    " all over the country. In 2009 Saaol opened its first international"
    " Center in Dhaka, Bangladesh and a year later in Nepal, Kathmandu."
    " Currently Dr. Chhajer has 110 centers across India and the "
    "subcontinent. Saaol Heart Center is now the largest chain of"
    " non-invasive cardiology clinics in the world. Brainchild of"
    " Dr. Chhajer, “Saaol Heart Program” today is a widely accepted "
    "treatment program for reversing heart disease – where in addition "
    "to the allopathic medicines, patients are taught yoga, meditation,"
    " zero oil cooking, stress management, exercise and medical knowledge."
    " Dr. Chhajer has authored about 70 books for heart patients and health, "
    "his numerous lectures are available in the form of DVD, Internet/You tube."
    " He is a magnificent teacher of preventive cardiology. Dr. Chhajer "
    "extensively travels all over India and world to promote non-invasive"
    " mode of treatment. He also publishes 2 monthly magazines on heart care."
    " He has treated over 4.5 lac heart patients successfully who could avoid "
    "bypass surgery or angioplasty. He has received many awards including "
    "Rajiv Gandhi Rashtriya Ekta award.";

const String patientInstructionTxt = "Every day, do a 35-minute walk on an empty stomach. If you have angina, your speed may be reduced. If you’re in bed or have just gotten out of an emergency, start with one minute per day and gradually increase up to 35 minutes.";
const String faqsTxt1 = "Yes. It's very easy to book appointment online with Dr. Bimal Chhajer. You just need to fill out our form and our team will connect with you and guide you for the process of online appointment booking which costs only Ru. 5000";
const String faqsTxt2 = "EECP (Enhanced External Counterpulsation) is a non-invasive treatment for heart disease that improves blood flow and cardiovascular health without surgery.";
const String faqsTxt3 = "Dr. Bimal Chhajer is the founder of SAAOL and a pioneer in non-invasive heart treatment in India, known for his innovative approaches to heart health.";
const String faqsTxt4 = "It is very easy to find the nearest center near to you for this you just need to visit the find nearest page and from there you can check you state and select for nearest center over there and visit for further process.";
const String faqsTxt5 = "Zero Oil Cooking involves preparing meals without any oil, helping to maintain heart health while ensuring the food remains tasty and nutritious.";
const String faqsTxt6 = "The SAAOL Detox program aims to cleanse the body, improve overall health, and support heart health through natural methods.";
const String centerTxt = "Enjoy our state-of-the-art facilities and services designed for holistic healing wellness in the Peaceful Valley Dehradun.";
const String therapiesTxt = "At SAAOL, we provide a raange of therapies and treatments tailored to meet individual needs.Our Comprehensive approach includes:";
const String aboutTherapiesTxt = "Our zero oil cooking technique ensures that you enjoy tasty and nutritious meals without the use of oil.Our chefs prepare a variety of dishes that are both healthy and delicious,supporting your heart wellness journey.";
const String aboutDetoxTxt = "Our detox therapy involves administering intravenous drips to cleanse your body of toxins,supporting optimal health and enhancing the body's natural healing process.";
const String aboutModernMedicineTxt = "SAAOL provides high-quality generic medications and supplements to patients at very reasonable prices. Our unwavering commitment ensures accessible and affordable healthcare for everyone,prompting well-being and health equity.";
const String ecpTxt = "By choosing SAAOL Heart Center for EECP Treatment in Aligarh, you're not just receiving medical care—you're embarking on a journey towards a healthier, happier life guided by experts who genuinely care about your well-being.";