const String aboutCenterTxt = "Experience cutting-edge heart care at the SAAOL Heart Center in Aligarh, specializing in innovative EECP treatment. Our center is dedicated to providing comprehensive care for patients facing heart diseases, including heart attack treatment, heart failure treatment, and heart disease management. We utilize advanced EECP therapy, also known as natural bypass therapy, delivering non-invasive solutions for patients with heart blockages, aiming to reverse heart disease and promote natural heart healing. At our state-of-the-art facility, we prioritize patient well-being by providing a range of services beyond EECP treatment. Our holistic approach includes detox therapy to support overall cardiovascular health and detoxification therapy treatment to address underlying factors contributing to heart disease. With a focus on non-invasive techniques, our center aims to provide effective cardio treatment for conditions such as coronary artery disease, ensuring optimal outcomes with minimal risk. Trust our experienced team at the Heart Center in Aligarh to deliver personalized care and transformative results for your heart health journey.";
const String benefit1 = "Unlike bypass surgery, EECP Therapy is non-invasive, meaning there are no incisions or cuts involved. Patients experience no trauma to the body, resulting in a quicker recovery time and minimal discomfort.";
const String benefit2 = "EECP Therapy is entirely painless. Patients can undergo treatment comfortably without the need for anesthesia or sedation. This eliminates the risks associated with anesthesia and post-operative pain management.";
const String benefit3 = "EECP Therapy is typically performed on an outpatient basis, meaning there's no need for hospitalization. Patients can return home immediately after treatment sessions, allowing them to resume their daily activities without interruption.";
const String benefit4 = "Since EECP Therapy doesn't involve any surgical incisions, the risk of infection is significantly reduced. Patients can undergo treatment with peace of mind, knowing that there's no risk of post-procedural complications.";
const String benefit5 = "EECP Therapy is associated with minimal to no side effects. Unlike traditional bypass surgeries, which can cause various adverse effects such as bleeding, infection, and allergic reactions to anesthesia, EECP Therapy provides a safe and well-tolerated alternative.";
const String aboutEECP = "Discover the power of EECP treatment, also called natural bypass therapy, for those seeking non-surgical heart attack treatments in Aligarh. Our mission is to treat and reverse heart disease effectively through non-invasive procedures. Find affordable solutions for a healthier heart journey with us.";
const String treatmentOverviewTxt = "SAAOL, has created a forte as the world’s largest chain of non-invasive heart centers having helped over 500,000 patients with a history of unsuccessful heart operations, re-blockages, low ejection fractions, etc. Our specialists are experts in diagnosing different heart problems without using any invasive methods such as any kind of fluid, injection, etc. Our treatment approach is based on allopathic modern medicine, fact-based medical tests, healthy dietary advice and lifestyle management which is far better and easy than surgical interventions.";
const String therapyTxt = "EECP therapy extends a compelling invitation for those navigating distinct challenges or personal preferences in their quest to address heart-relate issues. The following eligibility criteria shed light on who stands to benefit from EECP therapy:";
const String therapyTxt1 = "EECP therapy emerges as a particularly pertinent choice for individuals who do not meet the prerequisites for invasive interventions like surgical procedures. It presents an alternative avenue for tackling heart-relate ailments.";
const String therapyTxt2 = "EECP therapy proves invaluable for individuals carrying an elevated risk due to concurrent medical conditions. It serves as a non-invasive lifeline for those at risk of complications associated with surgical interventions.";
const String therapyTxt3 = "EECP therapy emerges as a particularly pertinent choice for individuals who do not meet the prerequisites for invasive interventions like surgical procedures. It presents an alternative avenue for tackling heart-relate ailments.";
const String therapyTxt4 = "When conventional medications fail to deliver the desired relief from angina or other heart-related symptoms, EECP therapy opens the door to renewed possibilities for enhanced heart health.";
const String therapyTxt5 = "EECP therapy steps forward as an effective option for individuals contending with the resurgence of symptoms following invasive treatments like angioplasty, stenting, or bypass surgery.";
const String therapyTxt6 = "EECP Therapy presents a viable and secure alternative for individuals whose medical conditions renders surgery impractical or places them at a substantial risk of postoperative complications.";
const String therapyTxt7 = "EECP therapy caters to those experiencing enduring chest pressure or discomfort, which varies with stress or physical exertion. It offers relief and contributes to overall heart wellness.";
const String preparingEECPTxt = "Before you embark on you Enhanced External Counterpulsation (EECP) therapy, a series of vital steps and preparations ensure a smooth and effective experience. Your path to improved heart health begins with thorough evaluation and thoughtful planning:";
const String preparingEECPTxt1 = "Medical Evaluation conducted by skilled healthcare professional. This assessment is to know your medical history, current health status, and the specific heart condition you are facing. The goal is to determine whether EECP is suitable and beneficial option to your needs.";
const String preparingEECPTxt2 = "Informative session to receive detailed information about EECP therapy. This session will equip you with a clear understanding of what to expect during the therapy, its potential benefits, and addresses any questions or concerns you may have.Health Monitoring throughout your EECP therapy sessions. Your vital signs, including blood pressure and heart rate, are closely monitored to ensure your safety and comfort throughout the process.";
const String preparingEECPTxt3 = "Setup for Best Comfort, reclining position on a specialised treatment bed. Large cuffs, like blood pressure cuffs but designed for precision, are gently secured around your calves, thighs and buttocks.";
const String preparingEECPTxt4 = "The therapy begins as these cuffs inflate and deflate in a synchronised manner, aligning with your own heartbeat. This inflation-deflation process assists in enhancing blood flow back to your heart, thereby reducing its workload and fastens healing.A typical EECP session is about an hour. During this time, you are encouraged to relax and unwind. Many individuals choose to read, watch TV, listen to music, or simply enjoy their peace time.A complete EECP course typically includes 35 sessions, scheduled over five days each week. This regimen extends over several weeks to optimize its benefits.";
const String preparingEECPTxt5 = "For many individuals, the positive effects of EECP therapy become evident even after just a few sessions. Reduced chest discomfort, increased vitality, and an overeall sense of wek-being often emerge as immediate benefits of EECP treatment.EECP treatment is an inspiration for positive lifestyle adjustments. Patients often find themselves adopting heart-healthy diets, embracing regular exercise routines, and incorporating stress management practices into their daily lives.Long-Term Benefits of EECP treatment like improved blood circulation, no more angina symptoms, and an enhanced quality of life are enduring advantages.Your healthcare team will arrange follow-up appointments to monitor your progress and address any further steps required to safeguard and enhance your heart health.";
const String preparingEECPTxt6 = "To get the full and remarkable benefits of EECP, it is important to continue practicing heart-healthy habits. This includes maintaining regular exercise, having a balanced diet, and, if prescribed, staying committed to your prescribed medication program.Remember, EECP treatment important treatment for your heart health. Ongoing communication with your healthcare professional and following their recommendations should be prioritized as it helps with your long-term well-being.";
const String safetyTxt = "This scientifically proven chart can be used by heart patients to check the status of their disease control.It contains 16 spokes in a wheel where each spoke represents a risk factor with parameters like cholesterol,triglycerides,cholesterol/HDL ratio,BP,sugar control,BMI,tobacco consumption,walking,intake of fats/ oils,consumption of fruits and vegetables,intake of animal foods,Yoga-based exercises,meditation,and stress management.There are three zones in this chart:";
const String aboutBimalSir = "Dr. Bimal Chhajer (MBBS, MD) is a prominent figure in medical science, recognized nationally and internationally for pioneering non-invasive cardiology in India. Born in 1961 into a Jain family, he spent his early years in a rural village in West Bengal. Demonstrating academic excellence from a young age, he completed his secondary education (matriculation) with excellent results from a local school in his hometown.";

const String blogTxt1 = "Heart health is paramount, yet it’s overlooked until problems arise. Understanding and undergoing essential heart tests can be a game-changer in early detection and prevention. This blog explores the crucial heart tests for blockage, their benefits, and how they help safeguard your heart health.";
const String aboutHearAttackTxt = "The most common complication of heart blockages—heart attack results in acute chest pain or breathlessness at rest. It is caused by 100% blockage of any of the coronary arteries. Simply put, the growing blockage stretches the membrane (Intima) covering the heart and ultimately rapturing it. Then clotting chemicals are released in the flowing blood making a clot that instantly stops the complete blood supply of the muscle getting from that particular tube. It happens suddenly and can kill a person suddenly. Heart Attacks may be minor, major, or massive depending on the location of the blockage. But is it preventable? –Yes with 98% surety!";
const String aboutTxtHeart = "Blood pressure is the measurement of the pressure or force of blood pushing against blood vessel walls. In high blood pressure (hypertension), this pressure against the blood vessel walls is consistently too high. High blood pressure is often called the ‘silent killer’ because you may not be aware that anything is wrong, but the damage is occurring within your body. The only way to find out if your blood pressure is high is to have your pressure checked. Untreated hypertension can increase your risk of stroke, heart failure, kidney failure, and other conditions.";
const String riskTxt = "If your blood pressure is too high, it puts added stress on your blood vessels, heart, and other organs, such as the brain, kidneys, and eyes. Persistent high blood pressure can surge your risk of a number of severe and potentially life-threatening health conditions such as heart diseases, heart attack, strokes, heart failure, peripheral arterial disease, aortic aneurysms, kidney diseases, and vascular dementia. If you have high blood pressure, reducing it to even a small amount can help lower your risk of these health conditions.";
const String treatmentTxt = "At Saaol we believe in non-invasive treatment methods that include education and lifestyle management, optimum allopathic medical management, and saaol detox therapy. We believe in effectively treating and reversing the condition by non-invasive methods. It is a combination of all-natural techniques to treat heart health conditions. We are promoters of yoga for heart and zero oil cooking. We have also created a Saaol safety circle to monitor how well are the hearth patients doing in their efforts.";
const String causesTxt = "High blood pressure, high blood cholesterol and smoking are key risks factors for heart disease. Several other medical conditions and lifestyle choice can put people at a higher risk for heart disease, including:";
const String causesTxt2 = "Heart disease is a common health problem. There are several types of heart diseases. In many cases, a person can take steps to prevent heart disease and its complications. The mission of Saaol is to effectively treat and reverse heart disease in a series of non-invasive or non-operative ways.";
const String magaZineTxt1 = "When it comes to staying healthy, your heart deserves top priority. Cardiovascular wellness is not just a medical concern; it's a lifestyle choice that significantly impacts your overall well-being. By adopting a heart-nourishing lifestyle, you can ensure your heart remains strong and resilient.";
const String conclusionTxt = "Adopting a heart-nourishing lifestyle is a journey worth embarking on. You can significantly improve your cardiovascular wellness by prioritizing diet, exercise, and mental well-being and avoiding harmful habits. Remember, your heart is at the center of your health, so take the steps today to ensure it stays healthy and strong.";
const String aboutSAAOLTxt = "SAAOL mission is to reduce the mortality rate due to heart disease related deaths and provide holistic heart care treatment and approach through natural bypass therapy, FDA approved non-invasive heart treatment like EECP and lifestyle changes. SAAOL Heart Centers are spread all over India so that people can have access to best heart treatment in India without travelling to Indian cities. Our heart specialists are trained under world renowned cardiologist Dr. Bimal Chhajer MBBS, MD (former AIIMS resident & associate professor). SAAOL ultimate purpose is to provide the best heart treatment and eradicate heart disease related deaths in India and then the world. Motto: Mission Beat Heart Disease.";
const String  visionTxt = "SAAOL’s vision is to ensure ‘Healthier Lifestyle and Risk Factor Reduction’. It aims to reduce the risk of heart disease through changes in Lifestyle which includes Diet Modification including Zero Oil Cooking, Stress Management, Exercise, Yoga, Meditation, Health Education and Counselling.";
const String missionTxt = "The mission of Saaol is to effectively treat and reverse heart disease by a series of non-invasive or non-operative ways. It combines all possible natural methods to treat heart disease and applies a simple theory of rectifying the causes of heart disease.";
const String valuesTxt = "To collaborate as a team and take extreme ownership of our audacious goals to achieve targets and display tremendous Integrity.";
const String aboutBimalSirTxt = "Dr. Bimal Chhajer MBBS, MD is a well-known personality in the world of medical science in India and abroad. He is the pioneer of Non-invasive cardiology in India. Born in 1961 in a Jain family, Dr. Chhajer grew up in a small village in West Bengal and passed his matriculation with flying colours from a local school. He studied in St. Lawrence high school in Kolkata thereafter and in 1986 pursued his MBBS from R.G. Kar Medical College, Kolkata. At the age of 25, he shifted to Delhi, where he started working in the cardiology department in Dr. Ram Manohar Lohia Hospital, New Delhi. A particular incident changed his life here and reformed his idea about the treatment of cardiac patients. He started advocating non-invasive or preventive cardiology. He then completed his MD in 1989 from king George’s Medical College, Lucknow where he took up a research study to treat heart patients using non-Invasive methods.";
const String aboutBimalSirTxt1 = "Post MD he worked at the famous All India Institute of Medical Sciences (AIIMS) for six years (1989-1995) as a Senior Resident and as an Assistant Professor. "
    "He also got training in yoga therapy. His research at the AIIMS"
    " showed that not only heart patients could prevent coronary"
    " heart disease but can also reverse or cure heart disease."
    " Dr. Chhajer during this stint also got trained by Dr."
    " Dean Ornish, who pioneered the lifestyle treatment in USA."
    " In 1995 based on his past research, Dr. Bimal chhajer resigned "
    "from AIIMS and started practically training and treating heart"
    " patients by his new treatment called “SAAOL” Science And Art Of "
    "Living in Delhi. In 1996 Dr. Chhajer opened his second clinic in "
    "Mumbai and subsequently expanded to Kolkata, Chennai, Bangalore"
    " and Hyderabad. These were followed by a spread of Saaol Centers"
    " all over the country. In 2009 Saaol opened its first international"
    " Center in Dhaka, Bangladesh and a year later in Nepal, Kathmandu."
    " Currently Dr. Chhajer has 110 centers across India and the "
    "subcontinent. Saaol Heart Center is now the largest chain of"
    " non-invasive cardiology clinics in the world. Brainchild of"
    " Dr. Chhajer, “Saaol Heart Program” today is a widely accepted "
    "treatment program for reversing heart disease – where in addition "
    "to the allopathic medicines, patients are taught yoga, meditation,"
    " zero oil cooking, stress management, exercise and medical knowledge."
    " Dr. Chhajer has authored about 70 books for heart patients and health, "
    "his numerous lectures are available in the form of DVD, Internet/You tube."
    " He is a magnificent teacher of preventive cardiology. Dr. Chhajer "
    "extensively travels all over India and world to promote non-invasive"
    " mode of treatment. He also publishes 2 monthly magazines on heart care."
    " He has treated over 4.5 lac heart patients successfully who could avoid "
    "bypass surgery or angioplasty. He has received many awards including "
    "Rajiv Gandhi Rashtriya Ekta award.";

const String therapiesTxt = "At SAAOL, we provide a raange of therapies and treatments tailored to meet individual needs.Our Comprehensive approach includes:";
const String aboutTherapiesTxt = "The interesting history of EECP (Enhanced External Counterpulsation) began in the early 1960s China, within the halls of a research laboratory where pioneering minds embarked on a journey to rewrite the narrative of heart health. In this innovative laboratory, EECP treatment became a reality. A unique contraption took place – a set of inflatable cuffs designed to encircle a patient’s legs. These cuffs soon emerged as the unsung heroes of cardiac care.";
const String aboutDetoxTxt = "Our detox therapy involves administering intravenous drips to cleanse your body of toxins,supporting optimal health and enhancing the body's natural healing process.";
const String lifeStyleTxt = "Our highly-specialized team firmly believes in non-invasive methods for treating heart-related problems across all age groups. Our medical treatment is based on the ancient wisdom shared over generations. After comprehensive research, our specialized team has narrowed down 4 different treatment protocols to treat heart diseases.";

const String aboutHeartPulse = "The heart rate, commonly referred to as the pulse, is the number of times your heart beats per minute (BPM). It is a vital indicator of your overall cardiovascular health and reflects how efficiently your heart is functioning to pump blood throughout the body. A normal resting heart rate typically ranges from 60 to 100 beats per minute for adults, though this can vary based on factors such as age, fitness level, and overall health.";
const String onBoardingTitle1 = "Book an Appointment with Dr. Bimal Chhajer";
const String onBoardingTitle2 = "Fast Pill Reminder – Never Miss a Dose";
const String onBoardingTitle3 = "Your Heart Health Tracker";
const String onBoardingDescription1 = "Easily schedule a consultation with Dr. Bimal Chhajer for expert heart care and guidance.";
const String onBoardingDescription2 = "Stay on top of your medication schedule with our quick and efficient pill reminder.";
const String onBoardingDescription3 = "Monitor your heart health with ease and keep track of important metrics for a healthier life.";
const String Call_team_txt = "You will receive a call back from our consultation team.Do you want to proceed?";
const String name = "Name*";
const String date_of_birth = "Date Of Birth*";
const String age = "Age*";
const String gender = "Gender*";
const String mobile_number = "Mobile Number*";
const String email = "Email*";
const String privacy_check = "By clicking 'Register' you agree to our Terms & Conditions as well as our Privacy Policy";
const String viwe_all = "View All";
const String check_haps_txt = "Check your haps report and you can download it";
const String call_chat_txt = "Call or Chat with a Health Expert";
const String need_help_txt = "Need Help? Talk to our health experts!";
const String DrBimal = "Dr.Bimal Chhajer";
const String Mbbs = "MBBS, MD, Founder | SAAOL";
const String Consulation_Phone = "8700083423";
const String wellnessLoction_txt = "You can reach us by road, rail, or air. We are conveniently located and easily accessible:";
const String wellnessByRoad_txt = "By Road: Follow the 14.4 km highway and look for signs directing you to the SAAOL Institute. The drive typically takes about 43 minutes.";
const String wellnessByRail_txt = "By Train: The nearest railway station is Dehradun, approximately 14.7 km from the institute, with a travel time of about 42 minutes.";
const String wellnessByAir_txt = "By Air: The closest airport is Jolly Grant Airport, situated approximately 48.6 km away. The journey usually takes around 1 hour and 30 minutes.";